name: crypto_price_tracker_app
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  get_it: ^7.2.0
  dio: ^5.1.1
  pull_to_refresh: ^2.0.0
  cached_network_image: ^3.2.3
  syncfusion_flutter_charts: ^22.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  freezed: ^2.2.1
  json_serializable: ^6.5.4
  logger: ^1.3.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

