# Название рабочего процесса
name: Notify in Telegram

# События, при которых запускается рабочий процесс
on:
  # При пуше в ветку dev
  push:
    branches: [ dev ]

# Задачи, которые выполняются в рабочем процессе
jobs:
  # Задача для сборки и тестирования флаттер приложения
  build:
    # Операционная система, на которой запускается задача
    runs-on: ubuntu-latest
    # Шаги, которые выполняются в задаче
    steps:
      # Шаг для установки флаттер SDK
      - name: Install Flutter SDK
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.8.1'
      # Шаг для клонирования репозитория с исходным кодом
      - name: Checkout repository
        uses: actions/checkout@v2
      # Шаг для получения зависимостей проекта
      - name: Get dependencies
        run: flutter pub get
      # Шаг для сборки проекта в режиме отладки
      - name: Build debug apk
        run: flutter build apk --debug
      # Шаг для запуска юнит-тестов
      - name: Run unit tests
        run: flutter test
      # Шаг для запуска интеграционных тестов
      - name: Run integration tests
        run: flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart
  # Задача для отправки оповещения в телеграм
  notifyTelegram:
    # Операционная система, на которой запускается задача
    runs-on: ubuntu-latest
    # Условие, при котором запускается задача
    if: always()
    # Шаги, которые выполняются в задаче
    steps:
      # Шаг для отправки сообщения в телеграм
      - name: Send message to Telegram
        uses: appleboy/telegram-action@master
        with:
          # Токен бота, который отправляет сообщение
          to: ${{ secrets.BOT_TOKEN }}
          # ID чата, в который отправляется сообщение
          token: ${{ secrets.CHAT_ID }}
          # Текст сообщения, который содержит статус рабочего процесса
          message: |
            👨🏾‍💻 Actor: ${{ github.actor }}
            🚀 Workflow: ${{ github.workflow }}
            🗂 Repository: ${{ github.repository }}
            🔎 Commit: ${{ github.sha }}
            🏷 Branch: ${{ github.ref }}
            🎯 Event: ${{ github.event_name }}
            🥇 Job: ${{ github.job }}
            🚦 Status: ${{ job.status }}
            🌐 URL: ${{ github.event.repository.url }}
